# Generated by Django 5.1.5 on 2025-06-21 07:32

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=student.models.student_directory_path),
        ),
    ]
